.PHONY: clean All

All:
	@echo "----------Building project:[ Blockchain - Debug ]----------"
	@cd "Blockchain" && "$(MAKE)" -f  "Blockchain.mk"
clean:
	@echo "----------Cleaning project:[ Blockchain - Debug ]----------"
	@cd "Blockchain" && "$(MAKE)" -f  "Blockchain.mk" clean
